from google.appengine.ext import webapp
from database import * #need this module to access datastore ...
import time #need this for timestamping ...

class Reneedit(webapp.RequestHandler):
   def get(self):
      #use key to fetch needit details from datastore and update timestamp ...
      needit = db.get(self.request.get("key"))
      needit.timestamp = int(time.time())
      needit.put()
      self.redirect('/myneeditslogin')
#end class Reneedit ...
