from google.appengine.ext.webapp.util import run_wsgi_app
from indexpage import * #contains requesthandler for handling requests to url '/' ...
from newspage import * #contains requesthandler for handing requests to url '/news' ...
from eventspage import * #contains requesthandler for handing requests to url '/events' ...
from sportspage import * #contains requesthandler for handing requests to url '/sports' ...
from politicspage import * #contains requesthandler for handing requests to url '/politics' ...
from campusespage import * #contains requesthandler for handing requests to url '/campuses' ...
from aboutpage import * #contains requesthandler for handing requests to url '/about' ...
from campusnewspage import * #contains requesthandler for handing requests to url '/campusnewspage' ...
from campuseventspage import * #contains requesthandler for handing requests to url '/campuseventspage' ...
from campussportspage import * #contains requesthandler for handing requests to url '/campussportspage' ...
from campuspoliticspage import * #contains requesthandler for handing requests to url '/campuspoliticspage' ...
from uploadpage import * #contains requesthandler for handing requests to url '/upload' ...
from getimage import * #contains requesthandler for serving images ... url '/images'
from getarticlepage import * #contains requesthandler for handing requests to url '/getarticle' ...
from breaknewspage import * #contains requesthandler for handing requests to url '/breaknews' ...
from newsaroundmepage import * #contains requesthandler for handing requests to url '/newsaroundme' ...
from viewmappage import * #contains requesthandler for handing requests to url '/viewmap' ...
from error import * #contains requesthandler for handling requests to url '/error' ...

application =  webapp.WSGIApplication([('/',Indexpage),
                                       ('/newspage',Newspage),
                                       ('/eventspage',Eventspage),
                                       ('/sportspage',Sportspage),
                                       ('/politicspage',Politicspage),
                                       ('/campuses',Campusespage),
                                       ('/breaknews',Breaknewspage),
                                       ('/newsaroundme',Newsaroundmepage),
                                       ('/viewmap',Viewmappage),
                                       ('/about',Aboutpage),
                                       ('/campusnewspage',Campusnewspage),
                                       ('/campuseventspage',Campuseventspage),
                                       ('/campussportspage',Campussportspage),
                                       ('/campuspoliticspage',Campuspoliticspage),
                                       ('/upload',Upload),
                                       ('/image',Getimage),
                                       ('/getarticle',Getarticlepage),
                                       ('/error',Error)
                                      ],
                                      debug=False)

def main():
   run_wsgi_app(application)

if __name__ == "__main__":
   main()
