from google.appengine.ext.webapp.util import run_wsgi_app
from needits import * #contains requesthandler for handling requests to url '/' ...
from about import * #contains requesthandler for handing requests to url '/about' ...
from login import * #contains requesthandler for handing requests to url '/login' ...
from blacklist import * #contains requesthandler for handing requests to url '/blacklist' ...
from needitslogin import * #contains requesthandler for handing requests to url '/needitslogin' ...
from signuplogin import * #contains requesthandler for handing requests to url '/signuplogin' ...
from logout import * #contains requesthandler for handing requests to url '/logout' ...
from myprofilelogin import * #contains requesthandler for handing requests to url '/myprofilelogin' ...
from getimage import * #contains requesthandler for handing requests to url '/getimage' ...
from postneeditlogin import * #contains requesthandler for handing requests to url '/postneeditlogin' ...
from myneeditslogin import * #contains requesthandler for handing requests to url '/myneeditslogin' ...
from getneedit import * #contains requesthandler for handling requests to url '/getneedit' ...
from reneedit import * #contains requesthandler for handling requests to url '/reneedit' ...
from remove import * #contains requesthandler for handling requests to url '/remove' ...
from search import * #contains requesthandler for handling requests to url '/search' ...
from searchlogin import * #contains requesthandler for handling requests to url '/searchlogin' ...
from admin import * #contains requesthandler for handling requests to url '/admin' ...
from error import * #contains requesthandler for handling requests to url '/error' ...

application =  webapp.WSGIApplication([('/',Needits),
                                       ('/about',About),
                                       ('/login',Login),
                                       ('/blacklist',Blacklist),
                                       ('/needitslogin',Needitslogin),
                                       ('/signuplogin',Signuplogin),
                                       ('/logout',Logout),
                                       ('/myprofilelogin',Myprofilelogin),
                                       ('/getimage',Getimage),
                                       ('/postneeditlogin',Postneeditlogin),
                                       ('/myneeditslogin',Myneeditslogin),
                                       ('/getneedit',Getneedit),
                                       ('/reneedit',Reneedit),
                                       ('/remove',Remove),
                                       ('/search',Search),
                                       ('/searchlogin',Searchlogin),
                                       ('/admin',Admin),
                                       ('/error',Error)
                                      ],
                                      debug=True)

def main():
   run_wsgi_app(application)

if __name__ == "__main__":
   main()
