from google.appengine.ext.webapp.util import run_wsgi_app
from ridesharekenya import * #contains requesthandler for handling requests to url '/' ...
from about import * #contains requesthandler for handing requests to url '/about' ...
from help import * #contains requesthandler for handing requests to url '/help' ...
from login import * #contains requesthandler for handing requests to url '/login' ...
from aboutlogin import * #contains requesthandler for handing requests to url '/aboutlogin' ...
from helplogin import * #contains requesthandler for handing requests to url '/helplogin' ...
from ridesharekenyalogin import * #contains requesthandler for handing requests to url '/ridesharekenyalogin' ...
from logout import * #contains requesthandler for handing requests to url '/logout' ...
from postridelogin import * #contains requesthandler for handing requests to url '/postridelogin' ...
from seekliftlogin import * #contains requesthandler for handing requests to url '/seekliftlogin' ...
from ridessharedaroundme import * #contains requesthandler for handling requests to url '/ridessharedaroundme' ...
from ridessharedaroundmenetwork import * #contains requesthandler for handling requests to url '/ridessharedaroundmenetwork' ...
from liftseekersaroundme import * #contains requesthandler for handling requests to url '/liftseekersaroundme' ...
from liftseekersaroundmenetwork import * #contains requesthandler for handling requests to url '/liftseekersaroundmenetwork' ...
from getrideshared import * #contains requesthandler for handling requests to url '/getrideshared' ...
from getliftseeker import * #contains requesthandler for handling requests to url '/getliftseeker' ...
from getimage import * #contains requesthandler for handling requests to url '/getimage' ...
from viewmappage import * #contains requesthandler for handling requests to url '/viewmap' ...
from myaccount import * #contains requesthandler for handling requests to url '/myaccount' ...
from addtonetwork import * #contains requesthandler for handling requests to url '/addtonetwork' ...
from viewaddtonetwork import * #contains requesthandler for handling requests to url '/viewaddtonetwork' ...
from mynetwork import * #contains requesthandler for handling requests to url '/mynetwork' ...
from viewmynetwork import * #contains requesthandler for handling requests to url '/viewmynetwork' ...
from declinerequest import * #contains requesthandler for handling requests to url '/declinerequest' ...
from dropconnection import * #contains requesthandler for handling requests to url '/dropconnection' ...
from error import * #contains requesthandler for handling request to url '/error' ...

application =  webapp.WSGIApplication([('/',RideshareKenya),
                                       ('/about',About),
                                       ('/help',Help),
                                       ('/aboutlogin',Aboutlogin),
                                       ('/helplogin',Helplogin),
                                       ('/login',Login),
                                       ('/ridesharekenyalogin',RideshareKenyalogin),
                                       ('/ridessharedaroundme',Ridessharedaroundme),
                                       ('/ridessharedaroundmenetwork',Ridessharedaroundmenetwork),
                                       ('/liftseekersaroundme',Liftseekersaroundme),
                                       ('/liftseekersaroundmenetwork',Liftseekersaroundmenetwork),
                                       ('/logout',Logout),
                                       ('/getimage',Getimage),
                                       ('/postridelogin',Postridelogin),
                                       ('/seekliftlogin',Seekliftlogin),
                                       ('/getrideshared',Getrideshared),
                                       ('/getliftseeker',Getliftseeker),
                                       ('/viewmap',Viewmappage),
                                       ('/myaccount',Myaccount),
                                       ('/addtonetwork',Addtonetwork),
                                       ('/viewaddtonetwork',Viewaddtonetwork),
                                       ('/mynetwork',Mynetwork),
                                       ('/viewmynetwork',Viewmynetwork),
                                       ('/declinerequest',Declinerequest),
                                       ('/dropconnection',Dropconnection),
                                       ('/error',Error)
                                       ],
                                      debug=False)

def main():
   run_wsgi_app(application)

if __name__ == "__main__":
   main()
